/**
# COPYRIGHT LICENSE:
# This information contains sample code provided in source code form. You may
# copy, modify, and distribute these sample programs in any form without
# payment to IBM for the purposes of developing, using, marketing or
# distributing application programs conforming to the application programming
# interface for the operating platform for which the sample code is written.
# Notwithstanding anything to the contrary, IBM PROVIDES THE SAMPLE SOURCE CODE
# ON AN "AS IS" BASIS AND IBM DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,
# INCLUDING, BUT NOT LIMITED TO, ANY IMPLIED WARRANTIES OR CONDITIONS OF
# MERCHANTABILITY, SATISFACTORY QUALITY, FITNESS FOR A PARTICULAR PURPOSE,
# TITLE, AND ANY WARRANTY OR CONDITION OF NON-INFRINGEMENT. IBM SHALL NOT BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES
# ARISING OUT OF THE USE OR OPERATION OF THE SAMPLE SOURCE CODE. IBM HAS NO
# OBLIGATION TO PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS OR
# MODIFICATIONS TO THE SAMPLE SOURCE CODE.
 **/

package com.ibm.jaxws.attachment.mtom;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_03-05/23/2007 04:33 PM(Raja)-fcs
 * Generated source version: 2.0
 *
 */
@WebServiceClient(name = "MtomSampleService",
                  targetNamespace = "http://com/ibm/jaxws/attachment/mtom/",
                  wsdlLocation = "wsdl/ImageDepot.wsdl")
public class MtomSampleService extends Service {

    private final static URL MTOMSAMPLESERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("file:wsdl/ImageDepot.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        MTOMSAMPLESERVICE_WSDL_LOCATION = url;
    }

    public MtomSampleService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MtomSampleService() {
        super(MTOMSAMPLESERVICE_WSDL_LOCATION, new QName("http://com/ibm/jaxws/attachment/mtom/", "MtomSampleService"));
    }

    /**
     *
     * @return
     *         returns MtomSample
     */
    @WebEndpoint(name = "MtomSamplePort")
    public MtomSample getMtomSamplePort() {
        return super.getPort(new QName("http://com/ibm/jaxws/attachment/mtom/", "MtomSamplePort"), MtomSample.class);
    }

}
